- id: '1788126644614'
  description: ''
  triggers:
  - trigger: time
    at: '23:50:00'
  conditions: []
  actions:
  - action: nordpool.get_prices_for_date
    metadata: {}
    data:
      date: '2026-08-31'
      config_entry: 01M06P1DCNXDYQY4KBZ5PVDZQP
    response_variable: nordpool_prices
  - action: persistent_notification.create
    data:
      title: Nord Pool test
      message: '{{ nordpool_prices }}'
  mode: single
- id: '1789560440549'
  alias: ttt
  description: ''
  triggers: []
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: kiosk_show_screensaver
    target:
      entity_id: notify.arvidsphoneold
  mode: single
- id: '1789560624523'
  alias: Increase brightness kiosk
  description: ''
  triggers: []
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    target:
      device_id: f54ede4a8f5e53134f485bbcd427afd2
    data:
      message: kiosk_set_brightness
      level: 0.5
  mode: single
